login:
    path: /
    controller: App\Controller\AdminController::index

viewAdmin:
    path: /viewAdmin
    controller: App\Controller\AdminController::viewAdmin

newInventory:
    path: /newInventory
    controller: App\Controller\AdminController::newInventory

casaHogar:
    path: /casaHogar
    controller: App\Controller\AdminController::listCasaHogar

centroMedico:
    path: /centroMedico
    controller: App\Controller\AdminController::listCentroMedico

controlPanel:
    path: /controlPanel
    controller: App\Controller\AdminController::controlPanel

transaccionProducto:
    path: /transaccionProducto
    controller: App\Controller\AdminController::transaccionProducto

usuariosGestion:
    path: /usuariosGestion
    controller: App\Controller\AdminController::usuariosGestion

patrimonio:
    path: /patrimonio
    controller: App\Controller\AdminController::listPatrimonio

gestionPatrimonio:
    path: /gestionPatrimonio
    controller: App\Controller\AdminController::gestionPatrimonio